version: "3.8"

services:
  sprinkler-rain-delay:
    image: craigham/sprinkler-rain-delay:latest
    networks:
      - services
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
    logging:
      driver: journald

networks:
  services:
    external: true
